exiftool -s -c "%.8f" * | \
 grep -v "^ExifToolVersion" |
 grep -v "^FileName" |
 grep -v "^Directory" |
 grep -v "^FileSize" |
 grep -v "^FileModifyDate" |
 grep -v "^FilePermissions" |
 grep -v "^FileType" |
 grep -v "^MIMEType" |
 grep -v "^JFIFVersion" |
 grep -v "^ResolutionUnit" |
 grep -v "^XResolution" |
 grep -v "^YResolution" |
 grep -v "^ExifByteOrder" |
 grep -v "LEAD Technologies Inc" |
 grep -v "^ImageWidth" |
 grep -v "^ImageHeight" |
 grep -v "^EncodingProcess" |
 grep -v "^BitsPerSample" |
 grep -v "^ColorComponents" |
 grep -v "^YCbCrSubSampling" |
 grep -v "^Make" |
 grep -v "^Model" |
 grep -v "^YCbCrPositioning" |
 grep -v "^ReferenceBlackWhite" |
 grep -v "^ExifVersion" |
 grep -v "^ComponentsConfiguration" |
 grep -v "^FlashpixVersion" |
 grep -v "^ColorSpace" |
 grep -v "^ExifImageWidth" |
 grep -v "^ExifImageHeight" |
 grep -v "^Orientation" |
 grep -v "^Software" |
 grep -v "^ModifyDate" |
 grep -v "^ExposureTime" |
 grep -v "^FNumber" |
 grep -v "^ISO" |
 grep -v "^CreateDate" |
 grep -v "^CompressedBitsPerPixel" |
 grep -v "^ExposureCompensation" |
 grep -v "^MaxApertureValue" |
 grep -v "^MeteringMode" |
 grep -v "^LightSource" |
 grep -v "^Flash" |
 grep -v "^FocalLength" |
 grep -v "Possibly incorrect maker notes offsets" |
 grep -v "^SpecialMode" |
 grep -v "^Quality" |
 grep -v "^Macro" |
 grep -v "^BWMode" |
 grep -v "^DigitalZoom" |
 grep -v "^FocalPlaneDiagonal" |
 grep -v "^LensDistortionParams" |
 grep -v "^CameraType" |
 grep -v "^CameraID" |
 grep -v "^DataDump" |
 grep -v "^FileSource" |
 grep -v "^Compression" |
 grep -v "^ThumbnailOffset" |
 grep -v "^ThumbnailLength" |
 grep -v "^Aperture" |
 grep -v "^ScaleFactor" |
 grep -v "^ShutterSpeed" |
 grep -v "^ThumbnailImage" |
 grep -v "^CircleOfConfusion" |
 grep -v "^FOV" |
 grep -v "^FocalLength" |
 grep -v "^HyperfocalDistance" |
 grep -v "^LightValue"
