
install:
	install itag-rename-files.pl ~/scripts
	install itag-set-dates.bash ~/scripts
	install itag-set-gps.bash ~/scripts
	install itag-gps-from-moves.pl ~/scripts
	install itag-check-date-geo.pl ~/scripts
